# File: 10_BASIC_array_job.R
# Auth: umar.niazi@kcl.as.uk
# DESC: create a parameter file and shell script to run array job on hpc
# Date: 04/04/2017


## set variables and source libraries
source('header.R')

## connect to mysql database to get sample information
library('RMySQL')

##### connect to mysql database to get samples
db = dbConnect(MySQL(), user='rstudio', password='12345', dbname='Projects', host='127.0.0.1')
dbListTables(db)

# check how many files each sample has
g_did
q = paste0('select count(File.idSample) as files, Sample.idData, Sample.title, Sample.id as SampleID from File, Sample
           where (Sample.idData = 12 and File.idSample = Sample.id) group by File.idSample')
dfQuery = dbGetQuery(db, q)
dfQuery$title = gsub(" ", "", dfQuery$title, fixed = T)
dfQuery

# get the count of files
q = paste0('select File.*, Sample.idData from File, Sample 
           where (Sample.idData = 12) and (File.idSample = Sample.id and File.type= "fastq") ')
dfCounts = dbGetQuery(db, q)
dfCounts$name = gsub(" ", "", dfCounts$name, fixed = T)
head(dfCounts)
nrow(dfCounts)
dfCounts

# for each sample id, get the corresponding files
cvQueries = paste0('select File.*, Sample.title from File, Sample 
                   where (Sample.idData = 12 and Sample.id =', dfQuery$SampleID, ') and (File.idSample = Sample.id and File.type = "fastq") ')

# set header variables 
cvShell = '#!/bin/bash'
cvShell.2 = '#$ -S /bin/bash'
cvProcessors = '#$ -pe smp 8'
cvWorkingDir = '#$ -cwd'
cvJobName = '#$ -N BASIC-array'
cvStdout = '#$ -j y'
cvMemoryReserve = '#$ -l h_vmem=19G'
cvArrayJob = paste0('#$ -t 1-', nrow(dfCounts)/2)
# using high memory queue with one slot and 19 Gigs of memory

# set the directory names
cvInput = 'input/'
cvOutput = 'output/BASIC/'
cvBowtie2 = '/opt/apps/bioinformatics/bowtie2/2.2.5/'


# create a parameter file and shell script
dir.create('AutoScripts')
oFile.param = file('AutoScripts/BASIC_param.txt', 'wt')

temp = sapply(cvQueries, function(x){
  # get the file names
  dfFiles = dbGetQuery(db, x)
  # check for null return
  if (nrow(dfFiles) == 0) return();
  # remove white space from title
  dfFiles$title = gsub(" ", "", dfFiles$title, fixed=T)
  # split the file names into paired end 1 and 2, identified by R1 and R2 in the file name
  f = dfFiles$name
  d = grepl('_R1_', f)
  d = as.character(d)
  d[d == 'TRUE'] = 'R1'
  d[d == 'FALSE'] = 'R2'
  lf = split(f, d)
  # write hisat2 command
  in.r1 = paste0(cvInput, 'trim_', lf[[1]])
  in.r2 = paste0(cvInput, 'trim_', lf[[2]])
  out.dir = paste0(cvOutput, as.character(dfFiles$title[1]))
  p1 = paste(in.r1, in.r2, out.dir, sep=' ')
  writeLines(p1, oFile.param)
})

close(oFile.param)

oFile = file('AutoScripts/BASIC.sh', 'wt')

writeLines(c('# Autogenerated script from BASIC_array_job.R ', paste('# date', date())), oFile)
writeLines(c('# make sure directory paths exist before running script'), oFile)
writeLines(c(cvShell, cvShell.2, cvProcessors, cvWorkingDir, cvJobName, cvStdout, cvMemoryReserve, cvArrayJob), oFile)
writeLines('\n\n', oFile)

# module load
writeLines(c('module load bioinformatics/bowtie2/2.2.5'), oFile)
writeLines(c('module load general/python/3.5.1'), oFile)
writeLines('\n\n', oFile)

## write array job lines
writeLines("# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=BASIC_param.txt
 
inr1=`sed -n ${number}p $paramfile | awk '{print $1}'`
inr2=`sed -n ${number}p $paramfile | awk '{print $2}'`
outdir=`sed -n ${number}p $paramfile | awk '{print $3}'`

# create the output directory
mkdir $outdir

# 9. Run the program.", oFile)
p1 = paste('python3.5 BASIC.py -p 8 -b', cvBowtie2, '-PE_1', '$inr1', '-PE_2', '$inr2', '-o', '$outdir', sep=' ')
com = paste(p1)

writeLines(com, oFile)
writeLines('\n\n', oFile)

close(oFile)
dbDisconnect(db)

